spring.application.name=sonic

# Server Port
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# External API Configuration
saavn.api.base-url=https://saavn.prakhar123srivastava.workers.dev
